- name: install nginx and php7
  yum:
    name:
      - nginx
      - php
      - php-cli
      - php-common
      - php-devel
      - php-fpm
      - php-mbstring
      - php-mysqlnd
      - php-pdo
      - php-gd
      - php-xml
  notify:
    - restart nginx

- name: modify php.ini
  replace:
    dest: /etc/php.ini
    regexp: "{{ item.regexp }}"
    replace: "{{ item.replace }}"
  with_items:
    - { regexp: "display_errors = Off", replace: "display_errors = On" }
    - { regexp: ";date.timezone =", replace: "date.timezone = Asia/Tokyo" }
    - { regexp: ";mbstring.language = Japanese", replace: "mbstring.language = Japanese" }
    - { regexp: ";mbstring.internal_encoding =", replace: "mbstring.internal_encoding = UTF-8" }
    - { regexp: ";mbstring.http_input =", replace: "mbstring.http_input = pass" }
    - { regexp: ";mbstring.http_output =", replace: "mbstring.http_output = pass" }
    - { regexp: ";mbstring.encoding_translation = Off", replace: "mbstring.encoding_translation = Off" }
    - { regexp: ";mbstring.detect_order = auto", replace: "mbstring.detect_order = UTF-8,SJIS,EUC-JP,JIS,ASCII" }
    - { regexp: ";mbstring.substitute_character = none", replace: "mbstring.substitute_character = none" }
    - { regexp: ";mbstring.func_overload = 0", replace: "mbstring.func_overload = 0" }
    - { regexp: ";mbstring.strict_detection = On", replace: "mbstring.strict_detection = Off" }
  notify:
    - restart nginx

- name: modify php-fpm config file
  replace:
    dest: /etc/php-fpm.d/www.conf
    regexp: "{{ item.regexp }}"
    replace: "{{ item.replace }}"
  with_items:
    - { regexp: "^user = apache", replace: "user = nginx" }
    - { regexp: "^group = apache", replace: "group = nginx" }
  notify:
    - restart php-fpm

- name: modify nginx.conf
  replace:
    dest: /etc/nginx/nginx.conf
    regexp: "{{ item.regexp }}"
    replace: "{{ item.replace }}"
  with_items:
    - { regexp: "80 default_server;", replace: "8080;" }
  notify:
    - restart nginx

- name: create the nginx config file
  template: src=role-web/templates/main.conf.j2 dest=/etc/nginx/conf.d/main.conf owner=root group=root mode=0644
  notify:
    - restart nginx

- name: change group session directory
  file: path=/var/lib/php/session state=directory group=nginx

- name: check composer
  stat: path=/usr/local/bin/composer
  register: composer_bin
  tags: composer

- block:
  - name: download composer
    get_url:
      url: https://getcomposer.org/installer
      dest: /tmp/installer

  - name: install composer
    shell: cat /tmp/installer | php -- --install-dir=/usr/local/bin

  - name: rename composer.phar to composer
    shell: mv /usr/local/bin/composer.phar /usr/local/bin/composer

  when: not composer_bin.stat.exists
  tags: composer

- name: check directory for main
  stat: path=/var/www/main
  register: directory_main
  tags: main

- block:
  - name: create directory for main
    file:
      dest: /var/www/main
      owner: "{{ web.username }}"
      group: "{{ web.username }}"
      mode: 0755
      state: directory

  - name: create directory for html
    file:
      dest: /var/www/main/html
      owner: "{{ web.username }}"
      group: "{{ web.username }}"
      mode: 0755
      state: directory

  - name: create the index file
    template: src=role-web/templates/index.php.j2 dest=/var/www/main/html/index.php owner="{{ web.username }}" group="{{ web.username }}" mode=0644

  when: not directory_main.stat.exists
  tags: main

- name: enable autostart for nginx
  service: name=nginx enabled=yes

- name: enable autostart for php-fpm
  service: name=php-fpm enabled=yes
