- name: install mariadb
  yum:
    name:
      - mariadb-server
      - MySQL-python
  notify:
    - restart mariadb

- name: create the configuration file
  template: src=role-db/templates/main.cnf.j2 dest=/etc/my.cnf.d/main.cnf owner=root group=root mode=0644
  notify:
    - restart mariadb

- name: enable autostart for mariadb
  service: name=mariadb enabled=yes
